[package]
name = "rithm"
description = "Arbitrary precision arithmetic."
license = "MIT"
license-file = "LICENSE"
version = "5.0.0-alpha"
edition = "2018"

[lib]
name = "rithm"
crate-type = ["cdylib", "rlib"]

[dependencies.pyo3]
version = "^0.14"
features = ["extension-module"]

[build-dependencies]
pyo3-build-config = "^0.14"
